// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmSwLFII1Z6q_LmTvYlLFk7KfVlTf9yK4',
    appId: '1:278696694583:web:9abafeb1e3b828971c40b2',
    messagingSenderId: '278696694583',
    projectId: 'geografiaapp',
    authDomain: 'geografiaapp.firebaseapp.com',
    storageBucket: 'geografiaapp.appspot.com',
    measurementId: 'G-KWS59RQG6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRWH68f_p6IzL72ts9IFmnXV6_mYpgag',
    appId: '1:278696694583:android:ab5e9a11045c3e291c40b2',
    messagingSenderId: '278696694583',
    projectId: 'geografiaapp',
    storageBucket: 'geografiaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEsvs8DQDRMDPQUYO1SI7S_-SspqDQ2xk',
    appId: '1:278696694583:ios:4a58e003a63cb5b81c40b2',
    messagingSenderId: '278696694583',
    projectId: 'geografiaapp',
    storageBucket: 'geografiaapp.appspot.com',
    iosBundleId: 'com.example.geografia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEsvs8DQDRMDPQUYO1SI7S_-SspqDQ2xk',
    appId: '1:278696694583:ios:f959fb34a22bd6c91c40b2',
    messagingSenderId: '278696694583',
    projectId: 'geografiaapp',
    storageBucket: 'geografiaapp.appspot.com',
    iosBundleId: 'com.example.geografia.RunnerTests',
  );
}
